#!/usr/bin/node
let url = 'https://cdn.learnenough.com/phrases.txt'
let request = require("request");
let Phrase = require("mhartl-palindrome");


request(url, function(error, response, body) {
  body.split("\n").forEach(function(line) {
    phrase = new Phrase(line);
    if (phrase.palindrome()) {
      console.log("palindrome detected:", line);
    }
  });
});
